---
version: "2.0"

services:
  ollama:
    image: ollama/ollama
    hostname: "ollama"
    ports:
      - "11434:11434"

  langserve:
    build:
      context: .
      dockerfile: Dockerfile.langserve
    environment:
      - "OLLAMA_HOST=ollama"
      - "COLLECTION=CYVERSE"
    hostname: "langserve"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./vectordb
        target: /opt/vectorstore
    depends_on:
      - ollama
